### ISSUE TITLE
Scale weight on restart goes to 0

### ISSUE THREAD

**Issue by Shabnata** [FatCatProject/FoodBox_Hardware#49]
Scale weight on restart goes to 0  even if it still has a food on the plate.

**Comment by FatCatProject** [comment]
1.Scale resets to zero after restart
2.feeding logs arent added to DB or showed.

**Comment by FatCatProject** [comment]
![1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5981cb25db8151001f93c910/125516c66e82c728ace21e0d46b9d6d6619291a685ecbc57e607b2c1701e24257b06f17874ddb02dbc122b555a5f1afa400a0b56e0ebcb7af8e2632dd3165eafc3674d75cf3710a9b8871bb807bd298f4a83b7aec7.png)
![2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5981cb25db8151001f93c910/125516c66e82c728ace21e0d46bad6d6619291a685ecbc57e607b2c1701e24257b06f17874ddb02dbc122b555a5f1afa400a0b56e0ebcb7af8e2632dd3165eafc3674d75ce3710a9b8871bb807bd298d4882b3aec7.png)

**Comment by Shabnata** [comment]
This branch is not in use, there was another version of branch 49 (#51)
Merge pull request #51 from FatCatProject/49-Second_Version  --> merged with master on Sep 11, 2017
Hence I've deleted this branch from git
